name: circtools primex (docker)


on:
  workflow_run:
    workflows: ["Multi-arch docker container", "Multi-arch docker nightly"]
    types: [completed]

concurrency:
  group: ci-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-primer-docker:
    name: circtools primer (Docker)
    runs-on: ubuntu-24.04
    env:
      GHCR_REPO: ghcr.io/jakobilab/circtools
    steps:
      - name: Set image tag based on triggering workflow
        run: |
          if [[ "${{ github.event.workflow_run.workflow }}" == "Multi-arch docker nightly" ]]; then
            echo "GHCR_IMAGE=${GHCR_REPO}:nightly" >> $GITHUB_ENV
          else
            echo "GHCR_IMAGE=${GHCR_REPO}:latest" >> $GITHUB_ENV
          fi
          echo "Using image: $(cat $GITHUB_ENV | grep GHCR_IMAGE)"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Pull image
        run: docker pull "${GHCR_IMAGE}"
      

      - name: Fix zcat on macOS
        if: runner.os == 'macOS'
        run: |
          sudo ln -sf $(which gzcat) /usr/local/bin/zcat

      - name: Unpack test dataset
        run: |
          tar xvf ./tests/data/circtools_example.tar.bz2
          cd circtools_example
          if [ -f genome.fa.gz ]; then gunzip -f genome.fa.gz; fi
          if [ -f annotation.gtf.gz ]; then gunzip -f annotation.gtf.gz; fi
          ls -lh

      - name: Run circtools primex (Docker)
        run: |
          cd circtools_example
          mkdir -p primer_output
          docker run --rm \
            -v "$(pwd):/host_rel/" \
            -v /:/host_os/ \
            -w /host_rel \
            "${GHCR_IMAGE}" \
            primex \
              -d ./circtools_ci_master/CircCoordinates \
              -f ./genome.fa \
              -g ./annotation.gtf \
              -O mm \
              -G Slc16a9 \
              -T "Slc16a9_primer" \
              -o ./primer_output/ || true

      - name: Inspect output
        run: |
          cd circtools_example/primer_output
          ls -la
          wc -l *

      - name: Check generated output against master
        run: |
          cd circtools_example/primer_output
          MASTER_DIR="../primer_output_master"
          diff Slc16a9_primer_primers.csv "$MASTER_DIR/Slc16a9_primer_primers.csv"
          sha1sum -c "$MASTER_DIR/sha1sums.txt"
